#### 1. Импортируйте пакет numpy под именем `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Создайте нулевой вектор размера 10 (★☆☆)

In [ ]:
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3. Как узнать объем памяти любого массива (★☆☆)

In [ ]:
print("объем памяти: ",
      null_vector.size * null_vector.itemsize)

объем памяти:  80


#### 4. Создайте вектор со значениями от 10 до 49. (★☆☆)

In [ ]:
vector_2 = np.arange(10,50)
vector_2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 5. Создайте обратный вектор из вектора в задании 4 (первый элемент становится последним) (★☆☆)

In [ ]:
reverse_vector_2 = vector_2[::-1]
reverse_vector_2

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 6. Создайте матрицу 3x3 со значениями от 0 до 8. (★☆☆)

In [ ]:
trian_matrix = np.arange(9).reshape((3,3))
trian_matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 7. Найти индексы ненулевых элементов из [1,2,0,0,4,0 (★☆☆)

In [ ]:
th = [1,2,0,0,4,0]
res = [i for i in range(len(th)) if th[i]!=0]
res

[0, 1, 4]

#### 8. Создайте массив 3x3x3 со случайными значениями (★☆☆)

In [ ]:
np.random.random((3,3,3))

array([[[0.58319699, 0.76951884, 0.41951109],
        [0.89306307, 0.97361994, 0.67521024],
        [0.04444073, 0.61070933, 0.42038959]],

       [[0.08468497, 0.50459558, 0.11476115],
        [0.79307144, 0.83168212, 0.7768983 ],
        [0.27624432, 0.8971805 , 0.9039685 ]],

       [[0.01248304, 0.650911  , 0.14649372],
        [0.15964472, 0.24225916, 0.27895324],
        [0.14900158, 0.69152873, 0.14372032]]])

#### 9. Создайте массив 10x10 со случайными значениями и найдите минимальное и максимальное значения. (★☆☆)

In [ ]:
mass = np.random.random((10,10))
print(mass,'\n')
print('max=>', mass.max(), ' min=>', mass.min())

[[0.75533486 0.06017025 0.35780005 0.35095303 0.53278924 0.53957841
  0.37828493 0.39237458 0.09508414 0.62723809]
 [0.01056277 0.119406   0.29959558 0.24286715 0.83492372 0.77357246
  0.79128106 0.57535395 0.38441129 0.24589528]
 [0.6341481  0.5520161  0.47673832 0.86176676 0.57619499 0.10299527
  0.7421336  0.40128503 0.98583001 0.16010207]
 [0.41020284 0.55613326 0.8637918  0.06189686 0.26687372 0.77815415
  0.74949093 0.73342945 0.93470155 0.2848099 ]
 [0.4716269  0.83875874 0.69398091 0.44674125 0.82097432 0.73507365
  0.70936045 0.08996758 0.33238469 0.08060213]
 [0.84015065 0.29798726 0.01240438 0.32337601 0.79131519 0.30525548
  0.72817748 0.42562101 0.14652413 0.86261407]
 [0.0389752  0.61217121 0.16966739 0.99856181 0.86637319 0.95386524
  0.19332625 0.66821125 0.90570185 0.30816249]
 [0.78025187 0.08381003 0.46696094 0.63968003 0.92139934 0.07593443
  0.18450219 0.50313151 0.75312993 0.20971646]
 [0.77844146 0.77220148 0.14752618 0.74299694 0.19946305 0.96898378
  0.10124478

#### 10. Создайте случайный вектор размера 30 и найдите среднее значение(★☆☆)

In [ ]:
np.random.random((30)).mean()

0.4363735540689612

#### 11. Создайте массив 2d 3x3 c 1 на границе и 0 внутри (★☆☆)

In [ ]:
m = np.ones((3,3))
m[1][1] = 0
m

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

#### 12. Каков результат следующего выражения? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
print('nan\nFalse\nFalse\nnan\nTrue\nFalse\n')

nan
False
False
nan
True
False



#### 13. Рассмотрим массив размера (6,7,8). Каков индекс (x,y,z) 100-го элемента? (★☆☆)

In [ ]:
mass = np.random.random((6,7,8))
indexs = np.where(mass == mass.reshape(6*7*8)[99])  # можно еще использовать np.ravel вместо reshape
print(*indexs[0],*indexs[1], *indexs[2])

1 5 3


#### 14. Умножить матрицу 5x3 на матрицу 3x2(★☆☆)

In [ ]:
a = np.random.random((5,3))
b = np.random.random((3,2))
np.dot(a,b)

array([[1.37159936, 0.65321739],
       [0.74051934, 0.41078291],
       [1.00602674, 0.31348069],
       [0.95190942, 0.53122929],
       [1.47695591, 0.66676567]])

#### 15. Создайте одномерный массив со случайными значениями от 1 до 10, инвертируйте (поменяйте местами) все элементы, со значениями 3 и 8. (★☆☆)

In [ ]:
mass_3 = np.random.randint(1, 11, size=20) #допустим размер такой
arr3 = np.where(mass_3 == 3)[0]
arr8 = np.where(mass_3 == 8)[0]
print('Текущий ->',mass_3)
if len(arr3)!=0 and len(arr8)!=0:
  for i in range(len(mass_3)):
    if i in arr3:
      mass_3[i] = 8
    elif i in arr8:
      mass_3[i] = 3
  print('Изменный ->',mass_3)
else:
  print('нет данных по условию в данном массиве, обновите данные')

Текущий -> [ 9  2  7  8 10  9  6  7  4  1 10  4  8  6  6  4  3  2  4 10]
Изменный -> [ 9  2  7  3 10  9  6  7  4  1 10  4  3  6  6  4  8  2  4 10]


#### 16. Каков результат следующих выражений? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-16-1f95df3dc0d5>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-16-1f95df3dc0d5>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 17. Как найти общие значения между двумя массивами? (★☆☆)

In [ ]:
aa = np.array([1,2,3,4,5,9,0,14])
bb = np.array([3,2,8,9,4,11,12,13])
np.intersect1d(aa,bb)

array([2, 3, 4, 9])

#### 18. Как вычислить ((A+B)*(-A/2)) с заменой массива А (без копирования)? (★★☆)

In [ ]:
A = np.random.randint(8, size=15)
B = np.random.randint(5, size=15)
A = (A+B)*(-A/2)
A

array([ -0.5,  -1.5,   0. ,  -8. , -18. ,   0. ,  -4.5, -12. , -30. ,
       -12.5,   0. ,   0. , -30. , -16. , -17.5])

#### 19. Создайте матрицу 5x5 со значениями строк от 0 до 4. (★★☆)

In [ ]:
np.array([np.arange(0, 5)] * 5)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 20. Создайте вектор размера 10 со значениями в диапазоне от 0 до 1, исключая 1 и 0 (★★☆)

In [ ]:
np.arange(0.05, 1, 0.1)

array([0.05, 0.15, 0.25, 0.35, 0.45, 0.55, 0.65, 0.75, 0.85, 0.95])

#### 21. Создайте случайный вектор размера 10 и отсортируйте его (★★☆)

In [ ]:
c = np.random.random(10)
print('now - ',c)
c.sort()
print('sorted - ',c)

now -  [0.06873323 0.43588009 0.00703641 0.26734042 0.89327701 0.41710006
 0.69395155 0.97852168 0.90944684 0.67195219]
sorted -  [0.00703641 0.06873323 0.26734042 0.41710006 0.43588009 0.67195219
 0.69395155 0.89327701 0.90944684 0.97852168]


#### 22. Можно ли суммировать небольшой массив быстрее, чем np.sum? (★★☆)

In [ ]:
import time

a = np.array([0,0,1,2,2,1])
start_time = time.time()
s = sum(a)
end_time = time.time()
print("sum function:", end_time - start_time)

from functools import reduce

start_time = time.time()
s = reduce(lambda x, y: x+y, a)
end_time = time.time()
print("reduce function:", end_time - start_time)


start_time = time.time()
s = 0
for i in a:
    s += i
end_time = time.time()
print("simple loop:", end_time - start_time)



sum function: 0.00011920928955078125
reduce function: 0.0001552104949951172
simple loop: 0.0001232624053955078


#### 23. Рассмотрим два случайных массива A и B, проверьте, равны ли они(★★☆)

In [ ]:
A = np.random.random(11)
B = np.random.random(11)
A == B

array([False, False, False, False, False, False, False, False, False,
       False, False])

#### 24. Создайте случайный вектор размера 10 и замените максимальное значение на 0 (★★☆)

In [ ]:
v = np.random.random(10)
print('before ->', v)
v[v==v.max()] = 0 #очень выручает в pandas
print('now ->', v)
# можно сделать через поиска индекса и замена по индексу, но это подольше будет

before -> [0.20498157 0.21561172 0.50553431 0.91430649 0.1335363  0.36424774
 0.62494536 0.294822   0.97900079 0.3301439 ]
now -> [0.20498157 0.21561172 0.50553431 0.91430649 0.1335363  0.36424774
 0.62494536 0.294822   0.         0.3301439 ]


#### 25. Распечатайте минимальное и максимальное представимое значение для каждого скалярного типа numpy (★★☆)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
   print(dtype, 'min =>', np.iinfo(dtype).min)
   print(dtype, 'max =>', np.iinfo(dtype).max, '\n')

for dtype in [np.float32, np.float64]:
   print(dtype, 'min =>',np.finfo(dtype).min)
   print(dtype, 'max =>',np.finfo(dtype).max, '\n')

<class 'numpy.int8'> min => -128
<class 'numpy.int8'> max => 127 

<class 'numpy.int32'> min => -2147483648
<class 'numpy.int32'> max => 2147483647 

<class 'numpy.int64'> min => -9223372036854775808
<class 'numpy.int64'> max => 9223372036854775807 

<class 'numpy.float32'> min => -3.4028235e+38
<class 'numpy.float32'> max => 3.4028235e+38 

<class 'numpy.float64'> min => -1.7976931348623157e+308
<class 'numpy.float64'> max => 1.7976931348623157e+308 



#### 26. Как вывести все значения большого массива? (★★☆)

In [ ]:
np.set_printoptions(threshold=1001)
print(np.arange(1001))

[   0    1    2    3    4    5    6    7    8    9   10   11   12   13
   14   15   16   17   18   19   20   21   22   23   24   25   26   27
   28   29   30   31   32   33   34   35   36   37   38   39   40   41
   42   43   44   45   46   47   48   49   50   51   52   53   54   55
   56   57   58   59   60   61   62   63   64   65   66   67   68   69
   70   71   72   73   74   75   76   77   78   79   80   81   82   83
   84   85   86   87   88   89   90   91   92   93   94   95   96   97
   98   99  100  101  102  103  104  105  106  107  108  109  110  111
  112  113  114  115  116  117  118  119  120  121  122  123  124  125
  126  127  128  129  130  131  132  133  134  135  136  137  138  139
  140  141  142  143  144  145  146  147  148  149  150  151  152  153
  154  155  156  157  158  159  160  161  162  163  164  165  166  167
  168  169  170  171  172  173  174  175  176  177  178  179  180  181
  182  183  184  185  186  187  188  189  190  191  192  193  194  195
  196 

#### 27. Рассмотрим случайный вектор формы (100,2), представляющий координаты, найдите расстояния между точками. (★★☆)

In [ ]:
r_v = np.random.random((100,2))
x,y = np.atleast_2d(r_v[:,0], r_v[:,1])
D =  np.sqrt( (x-x.T)**2 + (y-y.T)**2)
print(D,'\n')

[[0.         0.43452765 0.24598925 ... 0.37083336 0.26787833 0.76667642]
 [0.43452765 0.         0.60515092 ... 0.75762853 0.52245301 0.71437974]
 [0.24598925 0.60515092 0.         ... 0.15371539 0.48849562 0.66423996]
 ...
 [0.37083336 0.75762853 0.15371539 ... 0.         0.57279683 0.75261645]
 [0.26787833 0.52245301 0.48849562 ... 0.57279683 0.         1.02189865]
 [0.76667642 0.71437974 0.66423996 ... 0.75261645 1.02189865 0.        ]] 



#### 28. Как преобразовать массив с плавающей запятой (32 бита) в целое число (32 бита) с заменой?

In [ ]:
l = np.arange(15, dtype=np.float32)
l.astype(np.int32)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
      dtype=int32)

#### 29. Создайте массив из следующего файла: (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")

np.genfromtxt(s, delimiter=",")

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6., nan, nan,  7.,  8.],
       [nan, nan,  9., 10., 11.]])

#### 30. Вычтите среднее значение каждой строки случайной матрицы. (★★☆)

In [ ]:
import numpy as np
m = np.random.rand(3,2)
print('before ', m)
for mas in m:
  print('mean - ', mas.mean())
  mas -= mas.mean()
print('now ', m)

before  [[0.21715287 0.04665692]
 [0.50446239 0.39475426]
 [0.48716577 0.00873151]]
mean -  0.13190489131115396
mean -  0.4496083280279519
mean -  0.24794863784904497
now  [[ 0.08524798 -0.08524798]
 [ 0.05485406 -0.05485406]
 [ 0.23921713 -0.23921713]]


#### 31. Рассмотрим случайный вектор, как добавить 1 к каждому элементу, индексированному вторым вектором (будьте осторожны с повторяющимися индексами)? (★★★)

In [ ]:
vector_1 = np.random.rand(10)
indexs = np.array([8,3,6,2,1]) # например
for i in indexs:
  vector_1[i]+=1
print(vector_1)

[0.64622552 1.67210525 1.21959928 1.79077702 0.33852262 0.03375442
 1.33713833 0.69362808 1.41364017 0.711618  ]


#### 32. Как перенести элементы вектора (X) в массив (F) на основе списка индексов (I)? (★★★)

In [ ]:
X = np.random.randint(0, 15, size=10)
F = np.random.randint(0, 20, size=14)
I = np.random.randint(0,12, size=10)
print('from ->', X)
print('to ->', F)
print('indexs ->', I)

for i in range(10):
  F[I[i]] = X[i]

print('result ->', F)

print('result ->', np.bincount(I,X))

from -> [ 9  5  7  3  0 13 14  8 12 12]
to -> [ 5  9 10 19 14  1 14 19 18  5 16  4 14  2]
indexs -> [ 9  5  6  3 11  0  8  1  6  4]
result -> [13  8 10  3 12  5 12 19 14  9 16  0 14  2]
result -> [13.  8.  0.  3. 12.  5. 19.  0. 14.  9.  0.  0.]


#### 33. Рассматривая четырехмерный массив, как получить сумму сразу (в одну операцию) по двум последним осям? (★★★)

In [ ]:
A = np.random.randint(0,10,(2,2,2,2))
print(A,"\n")
print('sum ->', *A.sum(axis=(-2,-1)))

[[[[3 1]
   [4 6]]

  [[8 4]
   [0 6]]]


 [[[1 0]
   [8 9]]

  [[9 9]
   [5 5]]]] 

sum -> [14 18] [18 28]


#### 34. Рассмотрим вектор [1, 2, 3, 4, 5], как построить новый вектор с 3 последовательными нулями, чередующимися между каждым значением? (★★★)

In [ ]:
f = np.array([1, 2, 3, 4, 5])
new_f = np.zeros(len(f) + (len(f)-1)*(3))
new_f[::4] = f

print(new_f)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 35. Рассмотрим массив размерности (5,5,3), как его умножить на массив размерностью (5,5)? (★★★)

In [ ]:
trian = np.random.random((5,5,3))
print('massiv 5x5x3:\n',trian,'\n')
doub = np.random.random((5,5))
print('massiv 5x5:\n',doub,'\n')
doub = doub[:, :, np.newaxis]
print('multiplied:\n', np.multiply(trian, doub))

massiv 5x5x3:
 [[[0.32516277 0.30273077 0.38494621]
  [0.9018156  0.33004767 0.36195539]
  [0.41343221 0.65448065 0.25033005]
  [0.05419438 0.71961541 0.16373737]
  [0.84807979 0.17723936 0.55304525]]

 [[0.61359995 0.17625994 0.82918558]
  [0.01280302 0.80664984 0.03891089]
  [0.3744288  0.71958839 0.29369231]
  [0.40753707 0.74935683 0.34075561]
  [0.02978252 0.15893793 0.59583124]]

 [[0.07240336 0.07250416 0.6680409 ]
  [0.47102295 0.90153316 0.38766745]
  [0.58134371 0.70057986 0.85229616]
  [0.97084784 0.35806243 0.71768792]
  [0.54010726 0.3646009  0.14975042]]

 [[0.03174561 0.3917953  0.58655455]
  [0.10681046 0.30696622 0.52961868]
  [0.91503102 0.79062294 0.51492968]
  [0.95842571 0.61885692 0.88906769]
  [0.791897   0.66749211 0.92611675]]

 [[0.60398238 0.77378489 0.64916365]
  [0.36670269 0.38615015 0.59193941]
  [0.16180123 0.40642238 0.75928781]
  [0.35225278 0.11093666 0.67821319]
  [0.83189593 0.19030202 0.3385584 ]]] 

massiv 5x5:
 [[0.958116   0.58905139 0.78220157 

#### 36. Как вычислить средние значения, используя скользящее окно по массиву? (★★★)

In [ ]:
def moving_average(arr, window_size):
    n_windows = arr.shape[0] - window_size + 1

    # выходной массив для хранения средних значений
    avg_arr = np.zeros(n_windows)

    for i in range(n_windows):
        window = arr[i:i+window_size]
        avg_arr[i] = np.mean(window)

    return avg_arr

Z = np.arange(20)
print(moving_average(Z, 3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 37. Рассмотрим одномерный массив Z, постройте из него двумерный массив, первая строка которого (Z[0],Z[1],Z[2]), а каждая последующая строка сдвинута на 1 (последняя строка должна быть (Z[ -3],Z[-2],Z[-1]) (★★★)

In [ ]:
def shift_array(Z):
    n = Z.shape[0] - 2
    arr = np.empty((n, 3), dtype=Z.dtype)
    for i in range(n):
        arr[i] = Z[i:i+3]
    return arr

Z = np.arange(1, 10)
print(shift_array(Z))

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 38. Рассмотрим 2 набора точек P0,P1, описывающих линии (2d), и набор точек P. Как вычислить расстояние от каждой точки j (P[j]) до каждой линии i (P0[i],P1[i])?(★★★)

In [ ]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
P = np.random.uniform(-10, 10, (10,2))
# вычисляем различия между конечными точками линии и координатами точки
diff_P0_P = P0 - P[:, np.newaxis, :]
diff_P1_P = P1 - P[:, np.newaxis, :]

# вычисляем длины отрезков линии
seg_lengths = np.linalg.norm(diff_P1_P - diff_P0_P, axis=2)
# расстояния от каждой точки до каждой линии
cross_prod = np.cross(diff_P0_P, diff_P1_P, axis=2)
distances = np.abs(cross_prod) / seg_lengths

print(distances)

[[ 8.70372959  7.13927874  6.2607617   3.4371427   0.67311193 13.94269421
   0.80442725  3.51614797  8.23246178  9.06699926]
 [ 1.43559769  5.82154762  7.5275293   2.66169345 12.3489872   0.37619122
   3.87136122  6.77916988  1.70102064  1.1889546 ]
 [11.59647852  5.4642197  10.03817206  7.14658397  0.82278479 13.85172484
   4.14442052  5.58300783 11.27174491  6.20212485]
 [ 1.73191291 10.4293928   7.42760996  1.80588197 16.95758026  4.70012474
   6.13432636 10.95672058  1.21239646  4.600747  ]
 [ 1.55376702  1.6186515   5.00561257  0.68753554 10.3182383   3.80433288
   4.65938212  5.425427    1.55031442  3.03613349]
 [14.77486575  1.41510801 15.57242018 12.32147593  1.44791145 11.97719811
   8.2922422   7.19760886 14.75326331  0.80910413]
 [ 0.38317634  1.25819891  2.09922466  1.90791436  9.90953863  5.60797602
   6.48689834  5.60832789  0.17891909  6.43090721]
 [ 4.07487837  5.55602125  2.88770858  0.37669107  5.03286757 10.66259507
   3.61729308  1.05817199  3.64349836  9.31696429]


#### 39. Рассмотрим массив Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], как сгенерировать массив R = [[1,2,3, 4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [ ]:
Z = np.arange(1, 15)
R = np.reshape([Z[i:i+4] for i in range(11)], (11, 4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 40. Найдите ранг случайной матрицы (★★★)

In [ ]:
a = np.random.randint(0, 15, size=(4, 3))
np.linalg.matrix_rank(a)

3

#### 41. Как найти наиболее часто встречающееся значение в массиве?

In [ ]:
Z = np.random.randint(0,10,50)
# print(Z)
unique, counts = np.unique(Z, return_counts=True) # все уникальные и кол-во появления

def get_key(d, value):
    for k, v in d.items():
        if v == value:
            return k

dict_uniq = dict(zip(unique, counts))
print(get_key(dict_uniq, counts.max()))

1


#### 42. Рассмотрим два массива A и B формы (8,3) и (2,2). Как найти строки A, содержащие элементы каждой строки B, независимо от порядка элементов в B? (★★★)

In [ ]:
A = np.random.randint(0, 10, (8,3))
B = np.random.randint(0, 10, (2,2))


C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)

[5 7]


#### 43. Как извлечь уникальные значения из 2-х двумерных массивов?(★★★)

In [ ]:
C = np.random.random((3,3))
D = np.random.random((3,3))
print(np.unique(np.concatenate((C, D))))

[0.00638565 0.0282314  0.0472393  0.07436439 0.07769298 0.10034176
 0.15400036 0.18362504 0.24577692 0.25855645 0.25928734 0.34340892
 0.59827184 0.65265469 0.78099366 0.87456438 0.92957851 0.97025322]
